services:
  - type: worker
    name: tradeonai-backend-worker
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/stock_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: @kri$h@A
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: localhost:9092
      - key: SPRING_MAIL_USERNAME
        value: tradeonai50@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: ekmy maqu jcwm zauv
