services:
  - type: web
    name: tradeonai-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    rootDir: .
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-db-host:3306/stock_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: "@kri$h@A"
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: your-kafka-host:9092
      - key: MAIL_USERNAME
        value: tradeonai50@gmail.com
      - key: MAIL_PASSWORD
        value: ekmy maqu jcwm zauv
